### ISSUE TITLE
Points on county road

### ISSUE THREAD

**Issue by kaitlyngaynor** [kaitlyngaynor/hopland-hunting#15]
_From Alex e-mail_
> One thing I found in my notes from last time was that I did filter points above a certain speed (which was provided by igotus). That was to get rid of points on the county road. Since we can't do that for the HMM since it would mess up the even interval, perhaps we should add speed as a variable? Something to distinguish those points on the county road. 

Speed is one of the two dependent variables (well, step length is, but they are directly correlated since the time interval is always the same) so I think the HMM would already account for this (high step lengths are classified as 'driving' behavior). Does that make sense?

@amcinturff by county road are you referring to the road within the HREC boundaries? If so, I think we do want to include those anyway, right, since the hunters are still allowed to be hunting along this road?

**Comment by amcinturff** [comment]
Re the model accounting for speed, that sounds good.
Regarding the country road, my thought was that above a certain speed, they
are not actually going to be "hunting" in any real sense. Most of the
movement on this road at high speed is either going from one active hunting
area to another, or entering/exiting the site. Perhaps the model already
accounts for this, but I was concerned that the points on the county road
at high speed would be a distinct behavior that could add error to the
model if it isn't accounting for that. What do you think?

**Comment by kaitlyngaynor** [comment]
I don't think it's a huge issue since it will just get lumped in with the highest-speed class. Maybe I'm ignorant of how the models work but I think we can leave the points for now and just keep an eye on it. 

Re entering/exiting the site, these points will be removed when dividing into 'hunting bouts' so that will take care a lot of them anyway.
