### ISSUE TITLE
Some disconnected points from rest of track (due to missing points?)

### ISSUE THREAD

**Issue by kaitlyngaynor** [kaitlyngaynor/hopland-hunting#18]
Somewhat disconnected

- [x] 080815_04
- [x] 080815_11
- [ ] 080815_14
- [ ] 080915_02
- [ ] 080915_08
- [ ] 081217_34
- [ ] 081317_17
- [ ] 081317_34
- [ ] 081317_35
- [ ] 081416_07
- [ ] 081416_08
- [x] 081515_03
- [ ] 081917_37
- [ ] 082017_30
- [ ] 082215_04
- [ ] 082215_11
- [ ] 082215_16
- [ ] 082215_18
- [ ] 082315_02
- [ ] 082315_06
- [ ] 082315_09
- [ ] 082315_11
- [ ] 082315_14
- [ ] 082617_34
- [ ] 082816_05

More disconnected

- [ ]  081217_28
- [ ]   081217_37
- [ ]   081316_07
- [ ]   081317_37
- [ ]   081317_38
- [ ]   081615_08
- [ ]   081917_32
- [ ]   082017_33
- [ ]   082017_36
- [ ]   082116_17
- [ ]   082215_03
- [ ]   082215_17
- [ ]   082215_21
- [ ]   082315_03 (very weird)
- [ ]   082315_07 (very weird)
- [ ]   082617_35

**Comment by kaitlyngaynor** [comment]
Hmmm @amcinturff what do you think is going on here? This one in particular is odd... 

![Screen Shot 2021-12-14 at 9 41 21 AM](https://user-images.githubusercontent.com/29489999/146051207-053d3497-ef25-489c-8a47-10a4b2c42f14.png)

I had a look at the raw data at the end of the day (the red points on the map) and it looks like the logger just stopped recording at a fine interval. See here there is a 9 minute gap between 20:15:04 and 20:24:57

![Screen Shot 2021-12-14 at 9 46 41 AM](https://user-images.githubusercontent.com/29489999/146052036-f294059f-37e5-480f-a2fa-3b0cb8eb869c.png)

I guess maybe it's worth looking at time between subsequent steps, since really large gaps are going to cause an issue for us in the movement analysis. this is turning out to be FUN !

**Comment by amcinturff** [comment]
So fun. Since we have quite a large sample size in terms of total loggers,
I would not be opposed to tossing out ones where it looks like we have
logger issues. I am not sure the work to clean the data is worth it for the
marginal increase in inference. If I'm just being lazy, then we can do it.
I don't have any guesses about what is going on here other than a lightly
malfunctioning logger (though most of hte points seem ok?)

**Comment by kaitlyngaynor** [comment]
I think it would be best to do systematically, since "disconnected points" and "some disconnected points" are somewhat subjective designations. 

Assuming we are going to use a 3 minute fix interval, I'll do the following:

- If subsequent steps are <12 minutes apart (1, 2, or 3 points 'missing'), just interpolate based on location to determine the missing lat/long
- If steps are >12 minutes apart (4 or more points 'missing'), treat it as a separate track (and use hunter party as random effect in model)

Does that make sense? Is 4 missing points a good cutoff or do we want more?

But first I'll see how many steps we're talking about and how many tracks this would affect.

**Comment by kaitlyngaynor** [comment]
I had a look at fix rates for the cleaned 3 minute data. Doesn't seem to be a _huge_ issue although there are a handful of points with very, very long times between fixes (up to 70 minutes) so that will be a problem since HMM assumes 3 minutes for all steps when determining step length/speed.

Going to, instead, remove the step lengths in the top 5% when cleaning for HMM because they likely represent outliers or periods of logger malfunction. This is super easy! Not a huge data loss, either, but should sweep the issues under the rug. Should have thought of this sooner :) https://github.com/kaitlyngaynor/hopland-hunting/commit/32b8585d3ebb9b4a1f730234220dd2543cc06c2b

Still doesn't totally deal with weirdness of disconnected tracks. Next step: plot the points _after_ doing this 5% cleaning business and see if it's dealt with some of it. If not... ignore??

**Comment by kaitlyngaynor** [comment]
> Still doesn't totally deal with weirdness of disconnected tracks. Next step: plot the points _after_ doing this 5% cleaning business and see if it's dealt with some of it. If not... ignore??

Plotted the points. It doesn't look so weird anymore, but perhaps that's because there are fewer points so the outliers don't pop so much. Regardless, I think we can leave this issue be.

**Comment by amcinturff** [comment]
It sounds good intuitively - just curious how you landed on 4? Can we
justify that somehow?

**Comment by kaitlyngaynor** [comment]
This ended up being addressed instead with the 15 mph cut-off https://github.com/kaitlyngaynor/hopland-hunting/issues/25
