### ISSUE TITLE
Split tracks up for hunters that left the HREC site

### ISSUE THREAD

**Issue by kaitlyngaynor** [kaitlyngaynor/hopland-hunting#21]
_From Alex @amcinturff e-mail:_

> This is the trickiest one. We can't remove these points because we need the even interval. But clearly these are non-hunting points. Maybe we can make this a variable based on speed?

I think this is actually fairly simple, as we can just split into two different tracks—morning hunt, afternoon hunt. And include 'hunting party' as that random effect to account for the pseudoreplication issue. Sound ok?

- [ ] 081217_32
- [ ] 081316_03
- [ ] 081316_19
- [ ] 081317_30
- [ ] 081317_32
- [ ] 082116_05
- [ ] 082116_06
- [ ] 082116_07

**Comment by kaitlyngaynor** [comment]
@amcinturff this is a little tedious but could you perhaps manually investigate to figure out two 'start' and 'end' times for each of these tracks, so we can crop two different hunting periods (and thus remove the times when off the property)?

**Comment by amcinturff** [comment]
Yes, I can, is this only for the tracks listed? Ie,:
- 081217_32
- 081316_03
- 081316_19
- 081317_30
- 081317_32
- 082116_05
- 082116_06
- 082116_07

**Comment by kaitlyngaynor** [comment]
Yes, these are all of the tracks that you noted as "leaving the site" in your spreadsheet. Easiest if you can generate a spreadsheet with a row for each unique 'hunting bout' (probably 2 per individual) with columns:

- ID
- Hunting bout (1, 2, etc)
- Start time
- End time

**Comment by kaitlyngaynor** [comment]
Shouldn't need to do this after all; these points should be addressed by cropping to HREC https://github.com/kaitlyngaynor/hopland-hunting/commit/695ade2d58c5782ae6784fa60b05df29ca9160dc and then filtering points with very long step lengths

**Comment by amcinturff** [comment]
Ok, cool!
