### ISSUE TITLE
081917_38 doesn't move after 9am

### ISSUE THREAD

**Issue by kaitlyngaynor** [kaitlyngaynor/hopland-hunting#22]
@amcinturff you had marked this track as 'V' for very short. The specific issue seems to be that it returns to headquarters and doesn't move again, even though logger is marked as being returned at 19:40. 

![Screen Shot 2021-12-14 at 9 17 49 AM](https://user-images.githubusercontent.com/29489999/146047488-ba19b507-2d60-4670-81fa-c647de468f6c.png)

This logger traveled in a party with 081917_37—metadata reports them both returning at the same time, at 19:40, and this other track is more complete (see below). I would propose removing 081917_38 since it seems like the logger was perhaps accidentally left behind at HQ. Sound ok?

![Screen Shot 2021-12-14 at 9 20 47 AM](https://user-images.githubusercontent.com/29489999/146047925-cee04ce2-1f4b-4fc3-b210-a7a3834e46fe.png)

**Comment by amcinturff** [comment]
Agree, let's remove the offending track

**Comment by kaitlyngaynor** [comment]
Removed. https://github.com/kaitlyngaynor/hopland-hunting/commit/94399b614578b4b203aa66b2dc605c7b0bf7895e
